name: build-and-publish
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'stephengold' && startsWith(github.ref, 'refs/tags/') }}
    steps:
    - uses: actions/checkout@v6
    - name: Set up JDK 8
      uses: actions/setup-java@v5
      with:
        java-version: 8
        distribution: 'zulu'
        server-id: central
        server-username: ${{ secrets.NEXUS_USERNAME }}
        server-password: ${{ secrets.NEXUS_PASSWORD }}
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
    - name: Build and publish to Maven Central
      run: mvn deploy -DskipTests
